"use client";
import Skills from "@/components/Skills";
import Image from "next/image";

export default function Home() {
  return (
    <main className={`h-full w-full flex-1 flex flex-col justify-start items-center gap-20`}>      
      {/* <iframe src="https://facein-delta.vercel.app/" height={800} width={450} className="scale-75 rounded-box outline outline-1" /> */}
      <section className="mt-24 lg:mx-20 flex flex-col-reverse lg:flex-row justify-between items-center gap-16 divide-white">
        <div id="hero-text-container" className="flex-1 text-center lg:text-start">
          <h1 className="bg-gradient-to-br from-white to-slate-900 bg-clip-text text-transparent text-5xl lg:text-9xl font-semibold ">Wriddhi Hazra</h1>
          <p className="w-full lg:w-fit bg-gradient-to-r from-white to-slate-800 bg-clip-text text-transparent text-base lg:text-xl font-machina">Web App Developer from Kolkata, IN</p>
        </div>
        <div id="hero-image-container" className="flex-1 w-full h-full grid place-items-center relative">
          <Image priority id="hero-image-sm" src='/me-website.png' alt="Wriddhi Hazra" width={200} height={200} className="flex lg:hidden rounded-full relative" />
          <Image priority id="hero-image-lg" src='/me-website.png' alt="Wriddhi Hazra" width={400} height={400} className="hidden lg:flex rounded-full relative" />
          <span id="online" className="absolute -bottom-2 translate-y-full pl-8 pr-4 rounded-3xl bg-black outline outline-[#9742ff] text-[#9742ff]">Online</span>
        </div>
      </section>
      <section className="lg:my-20">
        <Skills />
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
      <section>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem libero, accusamus magnam deserunt sapiente iusto sequi repellendus reprehenderit iure numquam commodi dolorem maxime, nesciunt modi dolore praesentium cumque pariatur eligendi incidunt perferendis doloremque animi, suscipit temporibus quia? Minima ipsam reprehenderit, amet blanditiis nulla reiciendis aperiam neque et magni quaerat iusto eum recusandae consequatur quam sapiente, ipsum officiis at expedita? Facilis vero accusamus consectetur quo aperiam necessitatibus consequuntur ratione. Commodi tenetur repellendus nostrum cumque similique. Commodi, id hic. Tempora, esse mollitia quas omnis fugiat voluptate necessitatibus explicabo nemo optio sapiente cupiditate eius quidem autem deserunt ullam inventore deleniti eligendi tempore unde, laborum vero aspernatur. Aliquid facilis sapiente ex corrupti, culpa at sunt sed modi distinctio! Earum officia at repellat. Repellendus minus voluptatum ipsam rem, ducimus enim odit pariatur, recusandae voluptatem atque et aliquid dolor, labore molestiae. Consequatur molestiae enim atque et, porro maiores fugit. Deleniti eaque ut placeat excepturi dolores. Repellat libero beatae ratione est vel esse quos voluptatem impedit, autem nemo eum iure, cupiditate sapiente modi consequuntur pariatur nisi, consequatur repudiandae! Dolores hic necessitatibus magni deserunt rerum repellendus suscipit similique qui aut, aliquid totam sit in nesciunt velit possimus, consequuntur aliquam unde cum repellat. Ullam a ducimus quod commodi. Dolor.
      </section>
    </main>
  )
}
